### ISSUE TITLE
Secure Key Storage and Signing

### ISSUE THREAD

**Issue by tyb-dev** [usbarmory/usbarmory#78]
Hi there!

I'd like to use USB Armory MK II as a portable Certificate Authority. 

This means, I need to generate and store an ECC key pair in hardware, and use it to sign data. It is important that the key pair is not exportable or accessible in any way. What options do I have to accomplish this? 

- Is there a way to map the crypto hardware to /dev/tpm0 and use TPM libraries? 
- Can I use OpenSSL with a specific engine? 
- Any other ways?

If I understood correctly, the SE050 chip provides this functionality, but it's not clear how to use it. 

Thank you!

**Comment by abarisani** [comment]
Hello, rather than an issue this is more a question for the [discussion group](https://groups.google.com/g/usbarmory).

Concerning your use case I'd personally implement a [TamaGo](https://github.com/usbarmory/tamago) unikernel for this, see our [GoKey](https://github.com/usbarmory/GoKey) project as it provides a good reference for such a use case.

Particularly for OpenSSL integration see the [PKCS#11 token over RPC](https://github.com/usbarmory/GoKey?tab=readme-ov-file#pkcs11-token) functionality.

The USB armory does not feature TPM compatible hardware unless you can find an SE050 library that supports that, for any other SE050 use please refer to NXP documentation for the SE050 or related software.

Kind regards
